-- CreateTable
CREATE TABLE "wedding_info" (
    "id" TEXT NOT NULL,
    "weddingDate" TEXT NOT NULL,
    "ceremonyTime" TEXT NOT NULL,
    "cocktailTime" TEXT NOT NULL,
    "dinnerPartyTime" TEXT NOT NULL,
    "venueName" TEXT NOT NULL,
    "venueAddress" TEXT NOT NULL,
    "venueLink" TEXT,
    "venueLatitude" DOUBLE PRECISION,
    "venueLongitude" DOUBLE PRECISION,
    "dressCodeTitle" TEXT NOT NULL,
    "dressCodeDescription" TEXT NOT NULL,
    "dressCodeMen" TEXT NOT NULL,
    "dressCodeWomen" TEXT NOT NULL,
    "weatherSeason" TEXT NOT NULL,
    "weatherAvgTemp" TEXT NOT NULL,
    "weatherDescription" TEXT NOT NULL,
    "weatherRecommendations" TEXT NOT NULL,
    "parkingAvailable" BOOLEAN NOT NULL DEFAULT true,
    "parkingDescription" TEXT,
    "accommodationTitle" TEXT,
    "accommodationDescription" TEXT,
    "giftPolicy" TEXT,
    "childrenPolicy" TEXT,
    "photographyNote" TEXT,
    "scheduleNote" TEXT,
    "transportNote" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" TEXT,

    CONSTRAINT "wedding_info_pkey" PRIMARY KEY ("id")
);
